version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - .:/app
      - node_modules:/app/node_modules
volumes:
  node_modules:
